name: example
description: Example Dart Frog application with request validation feature.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  meta: ^1.15.0
  request_validator:
    path: ../

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
