### POST /person with valid data
POST http://localhost:8080/person
Content-Type: application/json

{
  "username": "thecodexhub",
  "age": 24,
  "email": "thecodexhubofficial@gmail.com",
  "gender": "male"
}

### POST /person with invalid Content-Type header
POST http://localhost:8080/person
Content-Type: application/xml

{
  "username": "thecodexhub",
  "age": 24,
  "email": "thecodexhubofficial@gmail.com",
  "gender": "male"
}

### POST /person with no username and age field
POST http://localhost:8080/person
Content-Type: application/json

{
  "email": "thecodexhubofficial@gmail.com",
  "gender": "male"
}

### POST /person with invalid email and gender
POST http://localhost:8080/person
Content-Type: application/json

{
  "username": "thecodexhub",
  "age": 24,
  "email": "abc",
  "gender": ""
}

### Query validation - with valid code
GET http://localhost:8080/person/2?code=101

### Query Validation - with no queries
GET http://localhost:8080/person/2

### Query Validation - with invalid query
GET http://localhost:8080/person/2?code=sandip
