name: request_validator
description: A middleware to validate request body before route handler, focused with Dart Frog.
version: 0.1.0
repository: https://github.com/thecodexhub/request-validator
issue_tracker: https://github.com/thecodexhub/request-validator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_frog: ^1.1.0
  meta: ^1.15.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
